### ISSUE TITLE
dependency problems prevent configuration of network-manager-sstp

### ISSUE THREAD

**Issue by blackat** [reliablehosting/sstp-client#4]
Hi,
I have downloaded the .deb packages and when I try to install the nework manager under Ubuntu 16.04 I get this error:

```
dpkg: dependency problems prevent configuration of network-manager-sstp:
  network-manager-sstp depends on libsstp-client0 (>= 1.10.0); however:
  version of libsstp-client0 on system is 1.0.10-0ubuntu3
```

I guess there is an issue in the dependency version, on sourceforge there is not a `libsstp-client0` with version 1.10.0 but 1.0.10.

Do you have please some hint to make it works?

**Comment by exactt** [comment]
I would suggest you use the PPA https://launchpad.net/~eivnaes/+archive/ubuntu/network-manager-sstp instead. Works perfectly for me.

**Comment by blackat** [comment]
@exactt thanks a lot :wink:
